services:
  gateway:
    build: ./gateway
    container_name: gateway
    environment:
      - REPLICA_URLS=http://replica1:3001,http://replica2:3002,http://replica3:3003
    ports:
      - "3000:3000"
    depends_on:
      replica1:
        condition: service_healthy
      replica2:
        condition: service_healthy
      replica3:
        condition: service_healthy
    restart: on-failure
    networks:
      - drawing-network

  replica1:
    build: ./replica1
    container_name: replica1
    environment:
      - REPLICA_ID=1
      - PORT=3001
      - REPLICA_URLS=http://replica1:3001,http://replica2:3002,http://replica3:3003
      - GATEWAY_URL=http://gateway:3000
      - MY_URL=http://replica1:3001
    ports:
      - "3001:3001"
    volumes:
      - ./replica1:/app          # bind mount — edit files → nodemon auto-reloads
      - /app/node_modules        # keep node_modules from image
    restart: on-failure
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3001/status"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - drawing-network

  replica2:
    build: ./replica2
    container_name: replica2
    environment:
      - REPLICA_ID=2
      - PORT=3002
      - REPLICA_URLS=http://replica1:3001,http://replica2:3002,http://replica3:3003
      - GATEWAY_URL=http://gateway:3000
      - MY_URL=http://replica2:3002
    ports:
      - "3002:3002"
    volumes:
      - ./replica2:/app
      - /app/node_modules
    restart: on-failure
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3002/status"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - drawing-network

  replica3:
    build: ./replica3
    container_name: replica3
    environment:
      - REPLICA_ID=3
      - PORT=3003
      - REPLICA_URLS=http://replica1:3001,http://replica2:3002,http://replica3:3003
      - GATEWAY_URL=http://gateway:3000
      - MY_URL=http://replica3:3003
    ports:
      - "3003:3003"
    volumes:
      - ./replica3:/app
      - /app/node_modules
    restart: on-failure
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3003/status"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - drawing-network

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - REACT_APP_GATEWAY_URL=http://172.22.246.81:3000
    ports:
      - "8080:3000"
    depends_on:
      - gateway
    restart: on-failure
    networks:
      - drawing-network

networks:
  drawing-network:
    driver: bridge
